### ISSUE TITLE
unable to use my shared folder from nas. is it capable ?

### ISSUE THREAD

**Issue by balajeek** [RouHim/this-week-in-past#123]
I have CIFS/SMB mount on my qnap nas for all the photos, I use them for PhotoPrism app and its able to find all my photos including sub-folders.  I used the same shared folder path when i created this docker-compose but still it can't find any, i get "Found 0 resources" in the log.

Please help.  Thanks.

**Comment by hajo62** [comment]
You might show your `docker-compose.yaml`.

**Comment by balajeek** [comment]
```
  this-week-in-past:
    image: rouhim/this-week-in-past
    volumes:
      - /share/PhotoPrism/:/resources:ro # mount read only
    ports:
      - "8090:8080"
    environment:
      SLIDESHOW_INTERVAL: 30
```
